using System.Diagnostics;
using ProjectEuler.Domain;
using ProjectEuler.Domain.Implementation;


Console.WriteLine("Welcome to Lucas' Project Euler solved problems!");
Thread.Sleep(1000);
List<IProblem> problems = LoadAllProblems();

Console.WriteLine($"{problems.Count} problem(s) found.");

foreach (var problem in problems)
{
    ProblemRunner.Run(problem);
}

static List<IProblem> LoadAllProblems()
{
    return new List<IProblem>
    {
        new MultiplesOfThreeAndFive
        {
            Id = 1,
            Url = "https://projecteuler.net/problem=1",
            Title = "Multiples of 3 and 5",
            Description = "If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.\nFind the sum of all the multiples of 3 or 5 below 1000."
        },
        new EvenFibonacciNumbers
        {
            Id = 2,
            Url = "https://projecteuler.net/problem=2",
            Title = "Even Fibonacci numbers",
            Description = "Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:\n1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...\nBy considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms."
        }
    };
}
