using System.Net.Http.Headers;

namespace ProjectEuler.Domain.Implementation;

public class EvenFibonacciNumbers : IProblem
{
    public int Id { get; set; }
    public required string Url { get; set; }
    public required string Title { get; set; }
    public required string Description { get; set; }

    //Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:\n1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...\nBy considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
    public decimal Solve()
    {
        int limit = 4_000_000;
        int a = 1;
        int b = 2;
        int sum = 0;

        while (b <= limit)
        {
            if (b % 2 == 0)
            {
                sum += b;
            }

            int temp = a + b;
            a = b;
            b = temp;
        }
        return sum;
    }
}
